.PHONY: install test

install:
	@. ../script/lib.sh; \
	dest="$$HOME/.config/touchegg/"; \
	maybe_mkdir "$$(dirname "$$dest")"; \
	copy_to touchegg/touchegg.conf "$$dest/touchegg.conf"

test:
	@echo touchegg test not yet implemented.
