# i3status configuration used by swaybar.

general {
        colors = true
        interval = 1
}

order += "read_file network_status"
order += "read_file power_status"
order += "read_file temperature_status"
order += "disk /"
order += "disk /home/jeff/images/"
order += "path_exists images"
order += "path_exists fs"
order += "path_exists backup"
order += "run_watch DHCP"
order += "run_watch VPN"
order += "wireless _first_"
order += "ethernet _first_"
order += "load"
order += "tztime local"

wireless _first_ {
        format_up = "W: (%essid - %quality) %ip"
        format_down = "W: down"
}

ethernet _first_ {
        format_up = "E: %ip (%speed)"
        format_down = "E: down"
}

read_file power_status {
        format = "%content"
        format_bad = ""
        path = "/home/jeff/.power-status"
}

read_file network_status {
        format = "%content"
        format_bad = ""
        path = "/home/jeff/.network-status"
}

read_file temperature_status {
        format = "%content"
        format_bad = ""
        path = "/home/jeff/.temperature-status"
}

run_watch DHCP {
        pidfile = "/var/run/dhclient*.pid"
}

run_watch VPN {
        pidfile = "/var/run/vpnc/pid"
}

tztime local {
        format = "%Y-%m-%d %H:%M:%S"
}

load {
        format = "Δ %1min"
}

disk "/" {
        prefix_type = "custom"
        format = "/:%avail"
}

disk "/home/jeff/images" {
        prefix_type = "custom"
        format = "images:%avail"
}

path_exists "images" {
        path = "/home/jeff/images/.mounted"
        format = "[images]"
        format_down = "-images"
}

path_exists "fs" {
        path = "/home/jeff/fs/.mounted"
        format = "[fs]"
        format_down = "-fs"
}

path_exists "backup" {
        path = "/backup/backup"
        format = "[backup]"
        format_down = "-backup"
}
